import test from 'node:test';
import assert from 'node:assert/strict';
import {MODULES,seedCRM,applyCRM,statusOf,parseCSV,agentNames} from '../dist/crm.js';
const now='2026-09-18T06:00:00Z',next='2026-09-19T06:00:00Z';
const create=()=>applyCRM(seedCRM(now),{type:'createLead',data:{name:'Workflow Test',phone:'9000000998',source:'Manual'}},now);
test('RNR preserves status through three attempts, marks fourth, creates drafts only',()=>{let r=create();for(let n=1;n<=4;n++){r=applyCRM(r.state,{type:'call',leadId:r.resultId,data:{outcome:'RNR',notes:'No response',next}},now);const l=r.state.leads.find(l=>l.id===r.resultId);assert.equal(l.rnrCount,n);assert.equal(statusOf(l),n===4?'RNR':'Initial');}assert.equal(r.state.drafts.length,4);assert.ok(r.state.drafts.every(d=>d.status==='Draft only'));});
test('transfer requires Manager and rejected action is atomic',()=>{const r=create(),before=JSON.stringify(r.state);assert.throws(()=>applyCRM(r.state,{type:'transfer',leadId:r.resultId,data:{owner:'Meera Rao',notes:'Transfer request'}},now,'Aarav Shah'),/Manager/);assert.equal(JSON.stringify(r.state),before);});
test('CSV parser supports quoted commas, escaped quotes and CRLF',()=>{const rows=parseCSV('name,phone,project\r\n"Sample, Buyer",9000000888,"Tower ""A"""\r\n');assert.equal(rows[0].name,'Sample, Buyer');assert.equal(rows[0].project,'Tower "A"');assert.throws(()=>parseCSV('name,phone\n"broken,123'),/Unclosed/);});
test('CSV import validates entire batch without partially applying duplicate data',()=>{const s=seedCRM(now),before=JSON.stringify(s);assert.throws(()=>applyCRM(s,{type:'importCSV',rows:[{name:'One',phone:'9000000888'},{name:'Two',phone:'9000000888'}],data:{kind:'Data'}},now),/already exists/);assert.equal(JSON.stringify(s),before);const r=applyCRM(s,{type:'importCSV',rows:[{name:'One',phone:'9000000888'}],data:{kind:'Data'}},now);assert.equal(r.state.sources.length,s.sources.length+1);});
test('bulk update propagates ownership and follow-up dates atomically',()=>{const s=seedCRM(now),ls=s.leads.filter(l=>!['Won','Lost'].includes(l.stage)).slice(0,2);const r=applyCRM(s,{type:'bulkUpdate',ids:ls.map(l=>l.id),data:{owner:'Meera Rao',next,notes:'Team rebalance'}},now);ls.forEach(l=>{assert.equal(r.state.leads.find(x=>x.id===l.id).owner,'Meera Rao');assert.equal(r.state.tasks.find(t=>t.leadId===l.id&&t.status==='Open').due,new Date(next).toISOString());});assert.throws(()=>applyCRM(s,{type:'bulkUpdate',ids:[ls[0].id,'missing'],data:{owner:'Meera Rao',notes:'Team rebalance'}},now),/active leads/);});
test('all module save forms have working domain actions',()=>{let s=seedCRM(now);for(const [key,spec]of Object.entries(MODULES)){const data={};for(const f of spec.fields){data[f.key]=f.type==='select'?f.choices[0]:f.type==='agent'?'Aarav Shah':f.type==='project'?'Cedar Heights':f.type==='lead'?s.leads.find(l=>l.stage==='Qualified').id:f.type==='asset'?s.modules.assets[0].id:f.type==='sale'?s.modules.sales[0].id:f.type==='date'?'2026-09-18':f.type==='datetime-local'?'2026-09-19T06:00':f.type==='number'?100:f.type==='tel'?'9000000880':f.type==='email'?'demo@example.test':f.type==='url'?'https://example.test/demo':f.type==='time'?'09:00':'Demo '+f.key;}if(key==='users'){data.name='New User';data.username='new.user';}if(key==='projects')data.name='New Project';const r=applyCRM(s,{type:'recordSave',module:key,data},now);s=r.state;const rows=key==='inventory'?s.inventory:s.modules[key];assert.ok(rows.some(x=>x.id===r.resultId),key+' saved');}});
test('newly created users can be assigned to leads',()=>{let r=applyCRM(seedCRM(now),{type:'recordSave',module:'users',data:{name:'New Rep',username:'new.rep',email:'new@example.test',role:'Executive',status:'Active',permissions:'Assigned records'}},now);assert.ok(agentNames(r.state).includes('New Rep'));r=applyCRM(r.state,{type:'createLead',data:{name:'Assigned Buyer',phone:'9000000889',owner:'New Rep',source:'Manual'}},now);assert.equal(r.state.leads.find(l=>l.id===r.resultId).owner,'New Rep');});
test('leave approval is blocked in rep view and allows Manager',()=>{const s=seedCRM(now);const data={employee:'Aarav Shah',type:'Casual',from:'2026-09-20',to:'2026-09-21',notes:'Personal leave',status:'Approved'};assert.throws(()=>applyCRM(s,{type:'recordSave',module:'leaves',data},now,'Aarav Shah'),/Manager/);assert.equal(applyCRM(s,{type:'recordSave',module:'leaves',data},now).state.modules.leaves[0].status,'Approved');});
test('asset cannot be allotted twice',()=>{const s=seedCRM(now),data={asset:'AST-1',employee:'Aarav Shah',date:'2026-09-18',status:'Assigned',notes:'Laptop issued'};const r=applyCRM(s,{type:'recordSave',module:'allotment',data},now);assert.equal(r.state.modules.assets[0].status,'Assigned');assert.throws(()=>applyCRM(r.state,{type:'recordSave',module:'allotment',data:{...data,employee:'Meera Rao'}},now),/already assigned/);});
test('builder registration keeps lead link and prevents duplicates',()=>{const r=create(),data={builder:'Demo Builder',project:'Cedar Heights',notes:'Requested registration'};const a=applyCRM(r.state,{type:'builderRegistration',leadId:r.resultId,data},now);assert.equal(a.state.registrations[0].leadId,r.resultId);assert.throws(()=>applyCRM(a.state,{type:'builderRegistration',leadId:r.resultId,data},now),/already registered/);});
test('sales history and booked lead stay linked',()=>{const s=seedCRM(now),l=s.leads.find(l=>l.stage==='Qualified');const r=applyCRM(s,{type:'recordSave',module:'sales',data:{leadId:l.id,project:'Cedar Heights',unit:'A-999',saleType:'Fresh',date:'2026-09-18',saleValue:8000000,incentive:80000,owner:l.owner,notes:'Sample booking recorded'}},now);assert.equal(statusOf(r.state.leads.find(x=>x.id===l.id)),'Booked');assert.equal(r.state.tasks.filter(t=>t.leadId===l.id&&t.status==='Open').length,0);assert.equal(r.state.modules.sales[0].leadId,l.id);});
test('editing cannot bypass visit or closed-lead transitions',()=>{const s=seedCRM(now),l=s.leads.find(l=>l.stage==='Qualified');assert.throws(()=>applyCRM(s,{type:'editLead',leadId:l.id,data:{name:l.name,phone:l.phone,notes:'Attempt bypass',status:'Site Visit Done'}},now),/site visit workflow/);});

