import test from 'node:test';
import assert from 'node:assert/strict';
import {seedState,applyAction,active,AGENTS} from '../dist/workflow.js';
const now='2026-09-18T06:00:00.000Z',next='2026-09-20T06:00:00.000Z';
const start=()=>applyAction(seedState(now),{type:'createLead',data:{name:'Demo Buyer',phone:'9000000999',source:'Manual'}},now);
const qualified=()=>{const r=start();return applyAction(r.state,{type:'call',leadId:r.resultId,data:{outcome:'Connected',requirement:'2 BHK',budget:8000000,project:'Cedar Heights',urgency:'1–3 months',notes:'Qualified customer',next}},now);};
test('intake creates owner, stage and exactly one first-call task',()=>{const r=start(),l=r.state.leads.find(l=>l.id===r.resultId);assert.equal(l.stage,'Live Initials');assert.ok(AGENTS.includes(l.owner));const ts=r.state.tasks.filter(t=>t.leadId===l.id&&t.status==='Open');assert.equal(ts.length,1);assert.equal(ts[0].kind,'First call');});
test('duplicate phones reject atomically after normalization',()=>{const r=start(),before=JSON.stringify(r.state);assert.throws(()=>applyAction(r.state,{type:'createLead',data:{name:'Duplicate',phone:'90000 00999',source:'Manual'}},now),/already exists/);assert.equal(JSON.stringify(r.state),before);});
test('connected call requires qualification and creates next task',()=>{const r=start();assert.throws(()=>applyAction(r.state,{type:'call',leadId:r.resultId,data:{outcome:'Connected',notes:'Customer answered',next}},now),/Requirement/);const q=qualified();assert.equal(q.state.leads.find(l=>l.id===q.resultId).stage,'Qualified');assert.equal(q.state.tasks.filter(t=>t.leadId===q.resultId&&t.status==='Open').length,1);});
test('RNR needs notes and future retry, remains active',()=>{const r=start();assert.throws(()=>applyAction(r.state,{type:'call',leadId:r.resultId,data:{outcome:'RNR',notes:'No answer',next:now}},now),/future/);const a=applyAction(r.state,{type:'call',leadId:r.resultId,data:{outcome:'RNR',notes:'No answer',next}},now);assert.equal(a.state.leads.find(l=>l.id===a.resultId).stage,'Contacting');});
test('site visit gates qualification and completion time',()=>{const r=start();assert.throws(()=>applyAction(r.state,{type:'scheduleVisit',leadId:r.resultId,data:{project:'Cedar Heights',when:'2026-09-19T06:00:00Z',next,notes:'Confirmed visit'}},now),/Qualify/);let q=qualified();q=applyAction(q.state,{type:'scheduleVisit',leadId:q.resultId,data:{project:'Cedar Heights',when:'2026-09-19T06:00:00Z',next,notes:'Confirmed visit'}},now);assert.throws(()=>applyAction(q.state,{type:'completeVisit',leadId:q.resultId,data:{notes:'Visited project',next}},now),/Advance/);q=applyAction(q.state,{type:'completeVisit',leadId:q.resultId,data:{notes:'Visited project',next}},'2026-09-19T08:00:00Z');assert.equal(q.state.leads.find(l=>l.id===q.resultId).stage,'Site Visit Done');});
test('transfer propagates open tasks and scheduled visits',()=>{let r=qualified();r=applyAction(r.state,{type:'scheduleVisit',leadId:r.resultId,data:{project:'Cedar Heights',when:'2026-09-19T06:00:00Z',next,notes:'Confirmed visit'}},now);const newOwner=AGENTS.find(a=>a!==r.state.leads.find(l=>l.id===r.resultId).owner);r=applyAction(r.state,{type:'transfer',leadId:r.resultId,data:{owner:newOwner,notes:'Territory reassignment'}},now);assert.equal(r.state.tasks.find(t=>t.leadId===r.resultId&&t.status==='Open').owner,newOwner);assert.equal(r.state.visits.find(v=>v.leadId===r.resultId).owner,newOwner);});
test('lost requires reason and cancels open work',()=>{let r=qualified();assert.throws(()=>applyAction(r.state,{type:'close',leadId:r.resultId,data:{outcome:'Lost',notes:'Not proceeding'}},now),/reason/);r=applyAction(r.state,{type:'close',leadId:r.resultId,data:{outcome:'Lost',reason:'Budget mismatch',notes:'Not proceeding'}},now);assert.equal(r.state.tasks.filter(t=>t.leadId===r.resultId&&t.status==='Open').length,0);assert.throws(()=>applyAction(r.state,{type:'followup',leadId:r.resultId,data:{notes:'Try again',next}},now),/closed/);});
test('won requires positive sale and valid closure date',()=>{let r=qualified();assert.throws(()=>applyAction(r.state,{type:'close',leadId:r.resultId,data:{outcome:'Won',notes:'Deal booked',saleValue:0,incentives:0,closedDate:'2026-09-18'}},now),/Sale value/);r=applyAction(r.state,{type:'close',leadId:r.resultId,data:{outcome:'Won',notes:'Deal booked',saleValue:8000000,incentives:0,closedDate:'2026-09-18'}},now);assert.equal(r.state.leads.find(l=>l.id===r.resultId).saleValue,8000000);});
test('seller and data conversion preserve origin and are idempotent',()=>{for(const sourceId of ['SEL-101','DAT-101']){const s=seedState(now);const r=applyAction(s,{type:'convert',sourceId,data:{target:'Lead'}},now);assert.equal(r.state.leads.find(l=>l.id===r.resultId).origin.id,sourceId);const again=applyAction(r.state,{type:'convert',sourceId,data:{target:'Lead'}},now);assert.equal(again.resultId,r.resultId);assert.equal(again.state.leads.length,r.state.leads.length);}});
test('inventory conversion validates and links source without removing it',()=>{const s=seedState(now);assert.throws(()=>applyAction(s,{type:'convert',sourceId:'DAT-101',data:{target:'Inventory'}},now),/required/);const r=applyAction(s,{type:'convert',sourceId:'SEL-101',data:{target:'Inventory',project:'Cedar Heights',unit:'A-1204',bhk:'3 BHK',area:1680,price:12000000}},now);assert.equal(r.state.sources.length,s.sources.length);assert.equal(r.state.inventory.find(i=>i.id===r.resultId).origin.id,'SEL-101');});
test('seed invariant: one open task per active lead, none for closed leads',()=>{const s=seedState(now);s.leads.forEach(l=>assert.equal(s.tasks.filter(t=>t.leadId===l.id&&t.status==='Open').length,active(l)?1:0));});

